app:
    resource: "@AppBundle/Controller/"
    type:     annotation

homepage:
    path: /{_locale}
    defaults:
        _controller: AppBundle:Default:index
        _locale: en
start:
    path: /
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: homepage
        permanent: true

flickrPhotos:
    path: /{_locale}/photos
    defaults:
        _controller: AppBundle:Default:getRecent
        _locale: en
    methods: [GET]
photos:
    path: /photos
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: flickrPhotos
        permanent: true

exploringMars:
    path: /{_locale}/mars
    defaults:
        _controller: AppBundle:Default:mars
        _locale: en
mars:
    path: /mars
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: exploringMars
        permanent: true
