app:
    resource: "@AppBundle/Controller/"
    type:     annotation

homepage:
    path: /{_locale}
    defaults:
        _controller: AppBundle:Default:index
        _locale: en
start:
    path: /
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: homepage
        permanent: true

flickrPhotos:
    path: /{_locale}/photos
    defaults:
        _controller: AppBundle:Default:getRecent
        _locale: en
    methods: [GET]
photos:
    path: /photos
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: flickrPhotos
        permanent: true

exploringMars:
    path: /{_locale}/mars
    defaults:
        _controller: AppBundle:Default:mars
        _locale: en
mars:
    path: /mars
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: exploringMars
        permanent: true

menu:
    path: /{_locale}/menu
    defaults:
        _controller: FrameworkBundle:Template:template
        template: load.html.twig
        _locale: en
#menu:
#    path: /{_locale}/menu
#    defaults:
#        _controller: AppBundle:Default:menu
#        _locale: en
menuRedirect:
    path: /menu
    defaults:
      _controller: FrameworkBundle:Redirect:redirect
      route: menu
      permanent: true

_wdt:
    resource: "@WebProfilerBundle/Resources/config/routing/wdt.xml"
    prefix:   /_wdt

_profiler:
    resource: "@WebProfilerBundle/Resources/config/routing/profiler.xml"
    prefix:   /_profiler
