app:
    resource: "@AppBundle/Controller/"
    type:     annotation

homepage:
    path: /{_locale}
    defaults:
        _controller: AppBundle:Default:index
        _locale: %locale%
    requirements:
        _locale: "%app.locales%"
start:
    path: /
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: homepage
        permanent: true

flickrPhotos:
    path: /{_locale}/photos
    defaults:
        _controller: AppBundle:Default:getRecent
        _locale: %locale%
    methods: [GET]
#photos:
#    path: /photos
#    defaults:
#        _controller: FrameworkBundle:Redirect:redirect
#        route: flickrPhotos
#        permanent: true

exploringMars:
    path: /{_locale}/mars
    defaults:
        _controller: AppBundle:Default:mars
        _locale: %locale%
#mars:
#    path: /mars
#    defaults:
#        _controller: FrameworkBundle:Redirect:redirect
#        route: exploringMars
#        permanent: true

menu:
    path: /{_locale}/menu
    defaults:
        _controller: AppBundle:Default:menu
        _locale: %locale%
menuRedirect:
    path: /menu
    defaults:
      _controller: FrameworkBundle:Redirect:redirect
      route: menu
      permanent: true

registration:
    path: /{_locale}/registration
    defaults:
        _controller: AppBundle:Default:register
        _locale: %locale%

admin:
    path: /admin
    defaults:
        _controller: AppBundle:Default:admin

showUsers:
    path: /{_locale}/show
    defaults:
        _controller: AppBundle:Default:show
        _locale: %locale%

login_route:
    path: /{_locale}/login
    defaults:
        _controller: AppBundle:Security:login
        _locale: %locale%
login:
    path: /login
    defaults:
          _controller: FrameworkBundle:Redirect:redirect
          route: login_route
          permanent: true
login_check:
  path: /login_check
  defaults:
      _controller: AppBundle:Security:loginCheck
logout:
  path: /logout

_wdt:
    resource: "@WebProfilerBundle/Resources/config/routing/wdt.xml"
    prefix:   /_wdt

_profiler:
    resource: "@WebProfilerBundle/Resources/config/routing/profiler.xml"
    prefix:   /_profiler
