app:
    resource: "@AppBundle/Controller/"
    type:     annotation

#homepage:
#    path: /
#    defaults: { _controller: AppBundle:Default:index }
#    methods: [GET]
homepage:
    path: /
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: flickrPhotos
        permanent: true
flickrPhotos:
    path: /{_locale}/photos
    defaults:
      _controller: AppBundle:Default:getRecent
      _locale: en
    methods: [GET]
photos:
    path: /photos
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: flickrPhotos
        permanent: true
test:
    path: /test
    defaults: { _controller: AppBundle:Default:test }