# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:

    encoders:
        AppBundle\Entity\User: bcrypt

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        chain_provider:
            chain:
                providers: [our_db_provider, in_memory]
        our_db_provider:
            entity:
               class: AppBundle:User
               property: _username
        in_memory:
            memory: ~

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        default:
            anonymous: ~
            pattern: ^/
            form_login:
                login_path: login_route
                check_path: login_check
                csrf_provider: security.csrf.token_manager
            logout:
              path: /logout
              target: /
            provider: our_db_provider
        main:
            anonymous: ~
            # activate different ways to authenticate

#            http_basic: ~
#            provider: our_db_provider
            # http://symfony.com/doc/current/book/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html

    role_hierarchy:
        ROLE_ADMIN: ROLE_USER

    access_control:
       - { path: ^/login$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
       - { path: ^/.*registration$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
       - { path: ^/.*photos, roles: ROLE_USER }
       - { path: ^/.*mars, roles: ROLE_ADMIN }
       - { path: ^/.*show$, roles: ROLE_ADMIN }
       - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY }