# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value
    request_parameters.endPoint: "https://api.flickr.com/services/rest"
    request_parameters.apiKey: "3bd97586d21ffcffe1931f53c2883652"
    request_parameters.format: "json"

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    request_parameters:
        class: AppBundle\Models\RequestParameters
        arguments: ["%request_parameters.endPoint%", "%request_parameters.apiKey%", "%request_parameters.format%"]

    curl:
        class: AppBundle\Models\CurlExec
        arguments: ["@request_stack"]

    app.locale_listener:
        class: AppBundle\EventListener\LocaleListener
        arguments: ["%kernel.default_locale%"]
        tags:
            - { name: kernel.event_subscriber }

    app.twig_extension:
      class: AppBundle\Twig\AppExtension
      public: false
      tags:
          - { name: twig.extension }

