# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value
    request_parameters.apiKey: "3bd97586d21ffcffe1931f53c2883652"
    request_parameters.format: "json"
    lunetics_locale.app_guesser.class: AppBundle\LocaleGuesser\AppLocaleGuesser

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    request_parameters:
        class: AppBundle\Models\FlickrPhoto\RequestParameters
        arguments: ["%request_parameters.apiKey%", "%request_parameters.format%"]

    curl:
        class: AppBundle\Models\FlickrPhoto\CurlExec
        arguments: ["@request_stack"]

    app.locale_listener:
        class: AppBundle\EventListener\LocaleListener
        arguments: ["%kernel.default_locale%"]
        tags:
            - { name: kernel.event_subscriber }

    app.twig_extension:
        class: AppBundle\Twig\AppTwigExtension
        public: false
        tags:
            - { name: twig.extension }
    mars_type:
        class: AppBundle\Models\Mars\MarsType
        arguments: ["@translator", "%form.textarea.attributes%"]

    lunetics_locale.app_guesser:
        class: "%lunetics_locale.app_guesser.class%"
        arguments: ["@lunetics_locale.validator.meta"]
        tags:
            - { name: lunetics_locale.guesser, alias: app }

#    app.locale_transform:
#        class: AppBundle\LocaleGuesser\AppLocaleTransform
#        arguments: ["%lunetics_locale.allowed_locales%"]

    registration_form_type:
        class: AppBundle\Models\Registration\RegistrationFormType
        arguments: ["@translator"]
